Repository microsoft/vs-threading, pull requests merged in 2018-08, with the labels that each got.

#346 Add CancellationToken.CombineWith extension methods
  src/Microsoft.VisualStudio.Threading.Tests/CancellationTokenExtensionsTests.cs
  src/Microsoft.VisualStudio.Threading/CancellationTokenExtensions.cs
Labels: enhancement

#342 Add test for field awaited in JTF run delegate
  src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
Labels: analyzers

#341 VSTHRD003 ignores ConfigureAwait for foreign tasks
  src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
  src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
  src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs
  src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs
Labels: analyzers

#347 Add SingleThreadedSynchronizationContext as public API
  src/Microsoft.VisualStudio.Threading.Tests/AsyncCountdownEventTests.cs
  src/Microsoft.VisualStudio.Threading.Tests/AsyncLazyInitializerTests.cs
  src/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs
  src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
  src/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs
  src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTestBase.cs
  src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
  src/Microsoft.VisualStudio.Threading.Tests/ProgressWithCompletionTests.cs
  src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreTestBase.cs
  src/Microsoft.VisualStudio.Threading.Tests/SingleThreadedSynchronizationContext.cs
  src/Microsoft.VisualStudio.Threading.Tests/SingleThreadedSynchronizationContextTests.cs
  src/Microsoft.VisualStudio.Threading.Tests/SingleThreadedTestSynchronizationContext.cs
  src/Microsoft.VisualStudio.Threading.Tests/TestBase.cs
  src/Microsoft.VisualStudio.Threading.Tests/TestUtilities.cs
  src/Microsoft.VisualStudio.Threading.Tests/ThreadingToolsTests.cs
  src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.cs.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.de.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.es.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.fr.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.it.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.ja.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.ko.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.pl.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.pt-BR.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.ru.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.tr.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.zh-Hans.xlf
  src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.zh-Hant.xlf
  src/Microsoft.VisualStudio.Threading/SingleThreadedSynchronizationContext.cs
  src/Microsoft.VisualStudio.Threading/Strings.Designer.cs
  src/Microsoft.VisualStudio.Threading/Strings.resx
Labels: enhancement

#368 Explain JTF.SwitchToMainThreadAsync cancellation
  src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
Labels: documentation
